version: '3'

services:
  drupal:
    build: .
    ports:
      - 8888:80
    volumes:
      - drupal_private:/var/www/private
      - ./sync:/var/www/sync
      - drupal_sites:/var/www/html/sites
      - drupal:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always

  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  drupal_private:
  drupal_sites:
  drupal:
  db_data:
